### PR TITLE
fix: convert from array to dictionary  in StripePlugin.swift

### LINKED ISSUE #1321: After confirm payment it throw a exception
**Describe the bug**
After complete payment stripe throw a Exception

**To Reproduce**
1. Entering number 4242 4242 4242 4242 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Smartphone / tablet**
 - Device: iPhone14 Simulator
 - OS: 16.4
 - Package version: 9.3.0
 
  Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision f468f3366c (7 giorni fa) • 2023-07-12 15:19:05 -0700
  Engine • revision cdbeda788a
  Tools • Dart 3.0.6 • DevTools 2.23.1

**Additional context**
Code: 
```
 Future<void> initStripe() async {
    if (paymentDataKey != null) {
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Main params
          merchantDisplayName: PaymentConstants.merchantDisplayName,
          paymentIntentClientSecret: paymentDataKey?.clientSecret,
        ),
      );
    } else {
      throw Exception();
    }
  }

  Future<bool> openPaymentSheet() async {
    try {
      await Stripe.instance.presentPaymentSheet();
      return true;
    } catch (error, stacktrace) {
      if (error is StripeException) {
        if (error.error.code == FailureCode.Canceled) {
          return false;
        }
      }
      log(error.toString());
      log(stacktrace.toString());
      throw Exception();
    }
  }
```

Exception: 
`type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>?'`

Stacktrace: 
```
MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:263:37)
      <asynchronous suspension>
      #1      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:517:12)
      <asynchronous suspension>
      #2      SlotPaymentController.openPaymentSheet (package: foo/controller/payment/slot_payment_controller.dart:40:7)
      <asynchronous suspension>
      #3      _SlotPaymentPageState.openPayment (package:foo/pages/payment/slot_payment_page.dart:164:11)
      <asynchronous suspension>

```

### PR DESCRIPTION
**Pull request by EliaTolin**
I recreate #1325 for convert list to map in StripePlugin.swift. 

Fixes #1321 

Co-authored-by: @jorger5 @jonasbark

### CODE REVIEW

**Comment by jonasbark** [comment]
looks good - did you test it as well?

**Comment by EliaTolin** [comment]
> looks good - did you test it as well?

I tested the field where this function is used, it seems to go correctly.

**Review by jonasbark — APPROVED** [review]

**Comment by jorger5** [comment]
Hi @EliaTolin looks good! It seems theres a typo in my username as co-author!

**Comment by EliaTolin** [comment]
> Hi @EliaTolin looks good! It seems theres a typo in my username as co-author!

Fix it, sorry! <3

**Comment by EliaTolin** [comment]
#1325

**Comment by EliaTolin** [comment]
Thanks you @jonasbark!

**Comment by RRosalia** [comment]
When will this be available on pubspec?

**Comment by jorger5** [comment]
> When will this be available on pubspec?

As it is already merged, you can point to the `main` branch in your pubspec.yaml, like this:

```
  flutter_stripe:
    git:
      url: https://github.com/flutter-stripe/flutter_stripe/
      ref: main
 ```
 
 it should work that way!

**Pull request merged**
