### PR TITLE
Refactor for platformPayCreatePaymentMethod error

### PR DESCRIPTION
**Pull request by EduardDumitrescu**
Refactor for -> https://github.com/flutter-stripe/flutter_stripe/issues/1879

### CODE REVIEW

**Review by WilliamCunhaCardoso — APPROVED** [review]

**Review by remonh87 — APPROVED** [review]
thanks looks good to me!

**Comment by remonh87** [comment]
can you resolve the conflicts?

**Comment by EduardDumitrescu** [comment]
> can you resolve the conflicts?

Resolved merge conflicts 👍

**Comment by kanghuicong** [comment]
I also found an issue: when I cancel Apple Pay, this listener method is ineffective: paymentRequest.onCancel(() {}). It is necessary to change

void onCancel(void Function() callback) {
    _js.on('cancel', ([_]) => callback);
}
to

void onCancel(void Function() callback) {
    _js.on('cancel', allowInterop(callback) as void Function(JSAny? v));
}

**Comment by dioseltorre** [comment]
@EduardDumitrescu Looks like some tests failed. Any updates on this?

**Comment by EduardDumitrescu** [comment]
> @EduardDumitrescu Looks like some tests failed. Any updates on this?

Hello, I don't quite understand  what I'm supposed to do with the tests. Locally they work and the error on the pipeline is 'IntegrationError: Please call Stripe() with your publishable key. You used an empty string.' . Maybe the pipeline is supposed to set the a stripe key and for some reason it doesn't on this pr?

**Comment by remonh87** [comment]
I decided to merge it because everything looks fine

**Pull request merged**
