### PR TITLE
Update stripe_platform_interface for stripe_web

### PR DESCRIPTION
**Pull request by davidmigloz**
With the latest release v9, dependencies are not resolving anymore if you depend on `stripe_web`. Because `stripe_web` is still depending on `stripe_platform_interface ^8.0.0`.

Error:
```
Running "flutter pub get" in app...
Resolving dependencies...
Because flutter_stripe_web >=3.0.0 depends on stripe_platform_interface ^8.0.0 and flutter_stripe >=9.0.0 depends on stripe_platform_interface ^9.0.0, flutter_stripe_web >=3.0.0 is incompatible with flutter_stripe >=9.0.0.
And because every version of payment_stripe from path depends on flutter_stripe 9.0.0+1, flutter_stripe_web >=3.0.0 is incompatible with payment_stripe from path.
So, because app depends on payment_stripe from path which depends on flutter_stripe_web 3.0.0, version solving failed.
```

### CODE REVIEW

**Review by remonh87 — APPROVED** [review]
thanks

**Comment by PatrikGolubar** [comment]
Hi, is this update available now or not? Can I use future payments on web version?
@jamesblasco @jonasbark

**Comment by RicharC293** [comment]
Maybe can you update this?
I tested with the last change in flutter_stripe_web and solve this issue
https://github.com/flutter-stripe/flutter_stripe/issues/960

**Comment by jamesblasco** [comment]
We are in the process to launch a new version that fixes several bugs from native and web. Should be launched today/tomorrow

**Comment by RicharC293** [comment]
Maybe an update for this?

**Comment by jjsebastianfuertes** [comment]
Hi @jamesblasco,
Any progress with the launch?

**Comment by jamesblasco** [comment]
This should be fixed by using
flutter_stripe_web: ^4.0.1
flutter_stripe: ^9.1.1

Let me know if you find any issues with this versiobs

**Pull request closed without merging**
