### PR TITLE
Fix PayPal payments

### PR DESCRIPTION
**Pull request by JonasWanke**
Fixes: #1211

The serialization of `MandateDataCustomerAcceptance` was incorrect: In Stripe's API, it corresponds to [a sealed union representing an `online` or an `offline` mandate](https://stripe.com/docs/api/setup_intents/confirm#confirm_setup_intent-mandate_data). In Stripe's Android SDK, it's [modelled the same way, though only `online` is supported](https://github.com/stripe/stripe-android/blob/1be82b108cba58e55893aea75fa7da4d5c640a68/payments-core/src/main/java/com/stripe/android/model/MandateDataParams.kt). To maintain backwards compatibility, I kept the existing class structure and only added custom `fromJson(…)` and `toJson(…)` implementations, though a cleaner design would probably be a named constructor `MandateDataCustomerAcceptance.online(…)`.

The other problem was that `PaymentMethodType` was missing a PayPal variant, meaning the native SDK's result message couldn't be parsed.

Now, payment and setup intents for subscriptions in Stripe are working for us both on Android and iOS with the following parameters:

```dart
const params = PaymentMethodParams.payPal(
  paymentMethodData: PaymentMethodData(
    mandateData: MandateData(
      customerAcceptance: MandateDataCustomerAcceptance(
        ipAddress: MandateDataOnlineData(
          ipAddress: '127.0.0.1',
          userAgent: 'device',
        ),
      ),
    ),
  ),
);
```

### CODE REVIEW

**Comment by remonh87** [comment]
@JonasWanke  thanks for the pr. Can you run `dart format` in your pr so we do not see the formatting changes in your pr?

**Comment by JonasWanke** [comment]
Hi @remonh87, I just ran `dart format .`, but it only changed another file. The first commit I pushed (https://github.com/flutter-stripe/flutter_stripe/pull/1341/commits/495a7fa3f5bb7f89074d3ca4db766a49fc84c101) was the result of running build_runner, which already changed the files. I'm guessing that either some formatting behavior changed or they were otherwise formatted differently before, since both the build_runner and `dart format` agree on the current formatting

**Review by remonh87 — APPROVED** [review]
thanks

**Comment by bonnyfone** [comment]
thanks for the fix! any timeline for when it will be published on pub.dev?

**Comment by artemsorochan** [comment]
Any timeline on publishing a new version with this MR would be appreciated. Thanks in advance!

**Comment by artemsorochan** [comment]
Any update on this?

**Pull request merged**
