### PR TITLE
Fixing issue with webview that was not dispalying anything by passing an initialUrl with https

### PR DESCRIPTION
**Pull request by nerder**
Fixes https://github.com/flutter-stripe/flutter_stripe/issues/683

### CODE REVIEW

**Comment by nerder** [comment]
Hey, there is any action missing from my side in order to get his merged?

**Comment by remonh87** [comment]
@jamesblasco  can you review this?

**Review by jamesblasco — APPROVED** [review]

**Comment by jamesblasco** [comment]
Hey @nerder, I am going to close this PR as you have this fix already in #894

**Comment by nerder** [comment]
Hey, yes makes total sense :)

**Pull request closed without merging**
