### PR TITLE
Add support for checking platform pay availability on web

### PR DESCRIPTION
**Pull request by cornwe19**
* Intended as first in a series of PRs to support platform pay on web
* Partially addresses #1122

### CODE REVIEW

**Comment by cornwe19** [comment]
@remonh87 @jonasbark @jamesblasco Looking for some feedback in particular on the interface change I had to make to `StripePlatform.isPlatformPaySupported` to support checking for PaymentRequest availability on web.

Let me know if there's some alternative method to supply the information Stripe JS needs that better fits with the structure of this SDK.

**Comment by cornwe19** [comment]
@remonh87 @jonasbark @jamesblasco Hey guys, any initial feedback on the direction I'm headed with this one? Thanks!

**Comment by cornwe19** [comment]
Planning to continue forward with a PR to start supporting actually rendering a [Payment Request Button](https://stripe.com/docs/stripe-js/elements/payment-request-button?client=html)

@remonh87 @jonasbark @jamesblasco  Curious if any of you have feedback on the direction I'm headed here before I start building off this code. Thanks, guys

**Comment by jonasbark** [comment]
Sorry for the lack of reply - we do not have a concept of how to move forward with Web support. Generally, I think your contribution looks good, thank you!

**Comment by cornwe19** [comment]
@jonasbark thanks for the approval. I fixed up some formatting that was triggering a build failure and rebased to get up to speed with main. Hoping next time checks run, this PR should be in good shape.

**Comment by cornwe19** [comment]
@jonasbark I'm noticing a couple of the status checks on this PR are failing for reasons that appear unrelated to code I've changed here.

I'm seeing errors like the following from stripe_js
`IntegrationError: Please call Stripe() with your publishable key. You used an empty string.`

and what appears to be a connectivity issue from the iOS integration tests
```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following ClientException was thrown running a test:
flutter: Connection closed before full header was received, uri=http://192.168.64.23:4242/payment-sheet
```

Are there any steps I need to take to resolve these?

**Comment by cornwe19** [comment]
@remonh87 @jonasbark @jamesblasco hey guys, is there anything blocking this PR from being merged? I have a follow up PR ready that fully implements the platform pay button UI and createPlatformPayPaymentMethod for web and I'm unsure if I should wait for this to be merged or just close this and open a larger PR with both the isPlatformPaySupported and createPlatformPayPaymentMethod methods implemented on web

**Comment by cornwe19** [comment]
Superseded by #1565

**Pull request closed without merging**
