### PR TITLE
add checkout redirect to web version

### PR DESCRIPTION
**Pull request by walid1001**
I didn't went in deep in the code but this worked

### CODE REVIEW

**Comment by walid1001** [comment]
ths worked for me

**Comment by remonh87** [comment]
LGTM @jamesblasco  can you check it out?

**Comment by walid1001** [comment]
any reviewer around ? kindly !

**Comment by jamesblasco** [comment]
Hey could you point out what was failing here? According to the official repo the error is parameter in the promise response 


Screenshot 2022-02-12 at 13 23 02

**Pull request closed without merging**
